### ISSUE TITLE
Is it possible to decipher the whole paths ?

### ISSUE THREAD

**Issue by blmhemu** [IGI-111/torrent-name-parser#3]
Is it possible to deciper the whole paths something like : https://jellyfin.org/docs/general/server/media/subtitles.html

**Comment by IGI-111** [comment]
It's not made for that, so no guarantees there, and I don't think it makes sense to make that a goal since paths are much more open ended. It's already pretty dicey to navigate all the common variations in one namespace.

Your best bet here is to use the folder names of each media or straight up file names stripped of extensions.
